version: '3'

volumes:
  postgres_volume_chat:

services:
  pg:
    image: postgres:14-alpine3.17
    env_file:
      - ".env"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume_chat:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure